---
AWSTemplateFormatVersion: 2010-09-09

Description: >
  fullbok-sg - SecurityGroup definition of JMeter cluster.

##############################################################################
##  CloudFormation Parameters
##############################################################################
Parameters:
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: >-
      The physical ID of the VPC for which the SecurityGroup is created.

  TargetPort:
    Type: Number
    Default: 80
    MinValue: -1
    MaxValue: 65536
    Description: >-
      The port number to open.

  JMeterInstancePublicIpAddresses:
    Type: String
    Description: >-
      Comma delimited list of public IP addresses of JMeter instances.
    AllowedPattern: '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}(,\s*\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2})*$'
    ConstraintDescription: >
      must be a comma delimited list of valid CIDR ranges of the form '1.2.3.4/32,5.6.7.8/32'.

  NamePrefix:
    Type: String
    Default: fullbok
    AllowedPattern: '[\w+=,.@-]+'
    MinLength: 1
    Description: >-
      Adds prefix string to resource names.
      (use hyphen instead of underscore)
    ConstraintDescription: >
      must be at least 1 or more characters in length.

  CommonTags:
    Type: String
    AllowedPattern: '^([\w_.:/+\-@]+=[\w_.:/+\-@]*)?(,\s*[\w_.:/+\-@]+=[\w_.:/+\-@]*)*$'
    Description: >-
      Comma delimited list of tags to be added to every resources.
      (in the form of 'Key=Value,Key2=Value2')
    ConstraintDescription: >
      must be a comma delimited list of valid Key-Value pairs in the form of Key=Value,Key2=Value2.

Metadata:
  ##############################################################################
  ##  Parameters Interface Configurations
  ##############################################################################
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: SecurityGroup Configuration
        Parameters:
          - VpcId
          - JMeterInstancePublicIpAddresses

      - Label:
          default: Additional Configuration
        Parameters:
          - NamePrefix
          - CommonTags

Resources:
##############################################################################
##  SecurityGroup
##############################################################################
  FullbokPublicSg:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Transform:
          Name: SnakeCase
          Parameters:
            InputString: !Sub ${NamePrefix}_public_sg
      GroupDescription: SecurityGroup for Public IP Addresses of Fullbok Slave Instances
      SecurityGroupIngress:
        Fn::Transform:
          Name: SpreadIngress
          Parameters:
            CidrIpList: !Ref JMeterInstancePublicIpAddresses
            Description: Rule for Fullbok Access
            IpProtocol: tcp
            FromPort: !Ref TargetPort
            ToPort: !Ref TargetPort
      VpcId: !Ref VpcId
      Tags:
        - Key: Application
          Value: !Ref AWS::StackId
        - Key: Name
          Value:
            Fn::Transform:
              Name: SnakeCase
              Parameters:
                InputString: !Sub ${NamePrefix}_public_sg
      Fn::Transform:
        Name: AppendTags
        Parameters:
          Tags: !Ref CommonTags
